[package]
name = "ThisCrow"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.3", features = ["v4", "serde"] }
jsonwebtoken = "8.1"
bcrypt = "0.10"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
log = "0.4"
env_logger = "0.9"
actix-ws = "0.2"
futures = "0.3"
futures-util = "0.3"
dashmap = "5.4"
sanitize-filename = "0.5"
actix-multipart = "0.7.0"
webrtc = "0.13.0"
webrtc-ice = "0.13.0"
once_cell = "1.21"
actix-cors = "0.7"
actix-files = "0.6"
tokio = "1.45"
paste = "*"