name: Build and Deploy

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  IMAGE_NAME: thiscrow
  DOCKERHUB_USERNAME: azizhankaya
  REMOTE_HOST: vate.world
  REMOTE_USER: root
  SQLX_OFFLINE: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "/opt/thiscrow" ]; then
              git clone --recurse-submodules https://github.com/${{ github.repository }} /opt/thiscrow
            else
              cd /opt/thiscrow && git fetch origin && git reset --hard origin/main
              git submodule update --init --recursive
            fi

            cd /opt/thiscrow/frontend && git fetch origin && git reset --hard origin/master

            rm -rf /var/www/thiscrow/*
            cp -r dist/* /var/www/thiscrow/

            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export SMTP_PASSWORD=${{ github.ref_name }}
            export VERSION_TAG=${{ github.ref_name }}

            docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            docker-compose -f /opt/thiscrow/docker-compose.yml down
            docker-compose -f /opt/thiscrow/docker-compose.yml up -d
